Models/Med.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace PharmaKursWork.Models
{
    public class Med
    {
        public int Id { get; set; }
        
        public string Name { get; set; }

        public DateTime StartExploring { get; set; }
        
        public decimal Expenses { get; set; }
        public string? Contraindications { get; set; }

        public int LabratoryId { get; set; }
        [ForeignKey(nameof(LabratoryId))]
        public Laboratory Laboratory { get; set; }

        [ForeignKey(nameof(CommodityGroupId))]
        public int CommodityGroupId { get; set; }
        public CommodityGroup CommodityGroup { get; set; }

        [ForeignKey(nameof(UnitMeasureId))]
        public int UnitMeasureId { get; set; }
        public UnitMeasure UnitMeasure { get; set; }
    }
}

ViewModels/MedViewModels/MedViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;

namespace PharmaKursWork.ViewModels.MedViewModels
{
    public class MedCustomViewModel
    {
        [DisplayName("Один")]
        public int Id { get; set; }

        [DisplayName("Назва")]
        public string Name { get; set; }

        [DisplayName("Початок розробки")]
        public DateTime StartExploring { get; set; }

        [DisplayName("Кінець розробки")]
        public DateTime EndExploring { get; set; }

        [DisplayName("Внесок")]
        public decimal Expenses { get; set; }

        [DisplayName("Лабораторія")]
        public string LabratoryName { get; set; }

        [DisplayName("Товарна група")]
        public string CommodityName { get; set; }

        [DisplayName("Одиниця виміру")]
        public string UnitMeasureName { get; set; }
    }

    public class MedViewModel
    {
        public List<MedCustomViewModel> List { get; set; } = new List<MedCustomViewModel>();

        public MedCustomViewModel MedCustomViewModel { get; set; }

        public SelectList LaboratoryList { get; set; }
        
        public SelectList CommodityGroupsList { get; set; }
        
        public SelectList UnitMeasuresList { get; set; }

        public FilterViewModel FilterViewModel { get; set; }

        public DonatProcedure Donat { get; set; }  
    }

    public class FilterViewModel
    {

        [DisplayName("Мінімальний внесок")]
        public decimal MinExpenses { get; set; }

        [DisplayName("Максимальний внесок")]
        public decimal MaxExpenses { get; set; }

        [DisplayName("Назва")]
        public string Name { get; set; }        
    }

    public class DonatProcedure
    {
        [DisplayName("Максимальний внесок")]
        public decimal Expenses { get; set; }

        public string Name { get; set; }
    }
}

Controllers/MedController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using PharmaKursWork.Models;
using PharmaKursWork.Servises;
using PharmaKursWork.ViewModels.MedViewModels;
using System.Data;
using System.Xml.Linq;

namespace PharmaKursWork.Controllers
{
    public class MedController : Controller
    {
        private readonly DataContext _db;
        private readonly UserServise _userServise;
        public MedController(DataContext db, UserServise userService)
        {
            _db = db;
            _userServise = userService;
        }
        [HttpGet]
        public async Task<IActionResult> Index(MedViewModel? medModel)
        {
            var user = _userServise.getCurrentUser();

            if (user == null || user.Username == "Guest")
            {
                return RedirectToAction("Index", "Account");
            }

            var filter = medModel.FilterViewModel;

            var labs = await _db.Laboratories.ToListAsync();
            var comGroups = await _db.CommodityGroups.ToListAsync();
            var unitMeasures = await _db.UnitMeasures.ToListAsync();
            var meds = (
                from m in _db.Meds
                join c in _db.CommodityGroups on m.CommodityGroupId equals c.Id
                join l in _db.Laboratories on m.LabratoryId equals l.Id
                join u in _db.UnitMeasures on m.UnitMeasureId equals u.Id
                select new MedCustomViewModel
                {
                    Id = m.Id,
                    Name = m.Name,
                    StartExploring = DateTime.Now,
                    Expenses = m.Expenses,
                    LabratoryName = l.Name,
                    CommodityName = c.Name,
                    UnitMeasureName = u.Name,
                }
            ).AsQueryable();

            if (filter != null)
            {
                if (!string.IsNullOrEmpty(filter.Name))
                {
                    meds = meds.Where(m => m.Name.Contains(filter.Name));
                }

                if (filter.MinExpenses > 0 && filter.MaxExpenses > 0)
                {
                    meds = meds.Where(m => m.Expenses > filter.MinExpenses && m.Expenses < filter.MaxExpenses);
                }
                else if (filter.MinExpenses > 0)
                {
                    meds = meds.Where(m => m.Expenses > filter.MinExpenses);
                }
                else if (filter.MaxExpenses > 0)
                {
                    meds = meds.Where(m => m.Expenses < filter.MaxExpenses);
                }
            }

            var model = new MedViewModel
            {
                LaboratoryList = new SelectList(labs, "Id", "Name"),
                CommodityGroupsList = new SelectList(comGroups, "Id", "Name"),
                UnitMeasuresList = new SelectList(unitMeasures, "Id", "Name"),
                List = await meds.ToListAsync(),
            };

            return View(model);
        }

        // Зміна інфи 
        [HttpGet]
        public async Task<IActionResult> EditMed(int id)
        {
            var rawMed = await _db.Meds.FirstOrDefaultAsync(m => m.Id == id);

            if (rawMed == default)
                return View("Index");

            var labs = await _db.Laboratories.ToListAsync();
            var comGroups = await _db.CommodityGroups.ToListAsync();
            var unitMeasures = await _db.UnitMeasures.ToListAsync();

            var med = new EditMedModel
            {
                Id = rawMed.Id,
                Name = rawMed.Name,
                StartExploring = rawMed.StartExploring,
                Expenses = rawMed.Expenses,
                LabratoryId = rawMed.LabratoryId,
                CommodityGroupId = rawMed.CommodityGroupId,
                UnitMeasureId = rawMed.UnitMeasureId,
            };

            var model = new EditMedModalViewModel
            {
                LaboratoryList = new SelectList(labs, "Id", "Name"),
                CommodityGroupsList = new SelectList(comGroups, "Id", "Name"),
                UnitMeasuresList = new SelectList(unitMeasures, "Id", "Name"),
                EditMedModel = med,
            };

            return PartialView(model);
        }
        // Редагування ліків
        [HttpPost]
        public async Task<IActionResult> EditMed(EditMedModalViewModel rawEditData)
        {
            var editData = rawEditData.EditMedModel;

            var med = (from m in _db.Meds where editData.Id == m.Id select m).FirstOrDefault();

            if (med == default)
                return View("Index");

            med.Name = editData.Name;
            med.StartExploring = editData.StartExploring;
            med.Expenses = editData.Expenses;
            med.LabratoryId = editData.LabratoryId;
            med.CommodityGroupId = editData.CommodityGroupId;
            med.UnitMeasureId = editData.UnitMeasureId;

            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> AddMed()
        {
            var labs = await _db.Laboratories.ToListAsync();
            var comGroups = await _db.CommodityGroups.ToListAsync();
            var unitMeasures = await _db.UnitMeasures.ToListAsync();

            var model = new AddMedModalViewModel
            {
                LaboratoryList = new SelectList(labs, "Id", "Name"),
                CommodityGroupsList = new SelectList(comGroups, "Id", "Name"),
                UnitMeasuresList = new SelectList(unitMeasures, "Id", "Name"),
            };
            return PartialView(model);
        }

        // додавання ліків до бази
        [HttpPost]
        public async Task<IActionResult> AddMed(AddMedModalViewModel rawMedData)
        {
            var medData = rawMedData.AddMedModal;
            var med = new Med
            {
                Name = medData.Name,
                StartExploring = DateTime.Now.Date,
                Expenses = medData.Expenses,
                LabratoryId = medData.LabratoryId,
                CommodityGroupId = medData.CommodityGroupId,
                UnitMeasureId = medData.UnitMeasureId,
            };

            await _db.Meds.AddAsync(med);
            await _db.SaveChangesAsync();


            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteMed(int id)
        {
            var med = (from c in _db.Meds where c.Id == id select c).FirstOrDefault();
            if (med == default)
                return View("Index");
            _db.Meds.Remove(med);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> HandleDonat(DonatProcedure donat)
        {
            if (donat.Expenses <= 0)
            {
                return RedirectToAction("Index");
            }

            object[] params1 = 
            {
                new SqlParameter("@medName", donat.Name),
                new SqlParameter("@donate", donat.Expenses),
            };

            _db.Database.ExecuteSqlRaw("addDonate {0}, {1}", params1);

            return RedirectToAction("Index");
        }
    }
}

Views/Med/AddMed.cshtml
@model PharmaKursWork.ViewModels.MedViewModels.AddMedModalViewModel;
@{
    Layout = null;
}

<div id="idi" class="modal fade" tabindex="-1" aria-labelledby="editModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Додати ліки</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-action="AddMed" asp-controller="Med">
                    <input type="hidden" asp-for="AddMedModal.Id" />
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="Name" class="col-form-label">@Html.DisplayNameFor(_ => Model.AddMedModal.Name)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="AddMedModal.Name" class="form-control" id="Name" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="expenses" class="form-label">@Html.DisplayNameFor(_ => Model.AddMedModal.Expenses)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input type="number" asp-for="AddMedModal.Expenses" class="form-control" id="expenses" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="lab" class="form-label">@Html.DisplayNameFor(_ => Model.AddMedModal.LabratoryId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="AddMedModal.LabratoryId" asp-items="Model.LaboratoryList" required></select>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="unitMesuare" class="form-label">@Html.DisplayNameFor(_ => Model.AddMedModal.UnitMeasureId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="AddMedModal.UnitMeasureId" asp-items="Model.UnitMeasuresList" required></select>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="commodityGroup" class="form-label">@Html.DisplayNameFor(_ => Model.AddMedModal.CommodityGroupId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="AddMedModal.CommodityGroupId" asp-items="Model.CommodityGroupsList" required></select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
                        <button type="submit" class="btn btn-primary">Додати</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Med/EditMed.cshtml
@model PharmaKursWork.ViewModels.MedViewModels.EditMedModalViewModel;
@{
    Layout = null;
}

<div id="idi" class="modal fade" tabindex="-1" aria-labelledby="editModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Змінити ліки</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-action="EditMed" asp-controller="Med">
                    <input type="hidden" asp-for="EditMedModel.Id" />
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="Name" class="col-form-label">@Html.DisplayNameFor(_ => Model.EditMedModel.Name)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="EditMedModel.Name" class="form-control" id="Name" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="expenses" class="form-label">@Html.DisplayNameFor(_ => Model.EditMedModel.Expenses)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input type="number" asp-for="EditMedModel.Expenses" class="form-control" id="expenses" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="lab" class="form-label">@Html.DisplayNameFor(_ => Model.EditMedModel.LabratoryId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="EditMedModel.LabratoryId" asp-items="Model.LaboratoryList" required></select>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="unitMesuare" class="form-label">@Html.DisplayNameFor(_ => Model.EditMedModel.UnitMeasureId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="EditMedModel.UnitMeasureId" asp-items="Model.UnitMeasuresList" required></select>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="commodityGroup" class="form-label">@Html.DisplayNameFor(_ => Model.EditMedModel.CommodityGroupId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="EditMedModel.CommodityGroupId" asp-items="Model.CommodityGroupsList" required></select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
                        <button type="submit" class="btn btn-primary">Змінити</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Med/Index.cshtml
@model PharmaKursWork.ViewModels.MedViewModels.MedViewModel
@inject PharmaKursWork.Servises.UserServise userService;
@{
    var isCurrentUserAdmin = userService.isCurrentUserAdmin();
}

<div class="text-center">
    <div>
        <form asp-action="Index" asp-controller="Med" method="get">
            <div class="mb-3 row align-items-center">
                <div class="col-auto">
                    <label for="MedName" class="col-form-label">@Html.DisplayNameFor(_ => Model.FilterViewModel.Name)</label>
                </div>
                <div class="col-auto flex-grow-1">
                    <input asp-for="FilterViewModel.Name" class="form-control" id="MedName">
                </div>
            </div>
            <div class="mb-3 row align-items-center">
                <div class="col-auto">
                    <label for="Expenses" class="col-form-label">@Html.DisplayNameFor(_ => Model.FilterViewModel.MinExpenses)</label>
                </div>
                <div class="col-auto flex-grow-1">
                    <input asp-for="FilterViewModel.MinExpenses" class="form-control" id="Expenses">
                </div>
            </div>
            <div class="mb-3 row align-items-center">
                
                
            </div>
            <button type="submit" class="btn btn-primary mt-2">Пошук</button>
        </form>
        <a class="btn btn-primary mt-2" asp-action="Index" asp-controller="Med">Зкинути</a>
    </div>
    <!-- Button trigger modal -->
    @if (isCurrentUserAdmin)
    {
        <button type="button"
            class="btn btn-primary ks-addbutton rounded-circle d-flex p-3 addButton"
            data-action="@Url.Action("AddMed", "Med")">
            <img style="width: 40px; height: 40px" src="icons/plus.svg" />
        </button>
    }
    <div>
        
    </div>
    <div class="modal-contaier">
        
    </div>
    @if (Model.List.Count > 0)
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <td></td>
                    <td>@Html.DisplayNameFor(_ => Model.MedCustomViewModel.Name)</td>
                    <td>@Html.DisplayNameFor(_ => Model.MedCustomViewModel.StartExploring)</td>
                    <td>@Html.DisplayNameFor(_ => Model.MedCustomViewModel.Expenses)</td>
                    <td>@Html.DisplayNameFor(_ => Model.MedCustomViewModel.LabratoryName)</td>
                    <td>@Html.DisplayNameFor(_ => Model.MedCustomViewModel.UnitMeasureName)</td>
                    <td>@Html.DisplayNameFor(_ => Model.MedCustomViewModel.CommodityName)</td>
                </tr>
            </thead>
            <tbody>

                @foreach (var med in Model.List)
                {
                    <tr>
                        <td class="align-middle">
                            @if (isCurrentUserAdmin)
                            {
                                <button class="ks-tablebuttons editButton" data-action="@Url.Action("EditMed", "Med", new { id = med.Id })"><img src="icons/pencil-square.svg" /></button>
                                <a class="ks-tablebuttons deleteButton" asp-action="DeleteMed" asp-controller="Med" asp-route-id="@med.Id"><img src="icons/trash3-fill.svg" /></a>
                            }
                        </td>
                        <td class="align-middle">@med.Name</td>
                        <td class="align-middle">@med.StartExploring</td>
                        <td class="align-middle">@med.Expenses</td>
                        <td class="align-middle">@med.LabratoryName</td>
                        <td class="align-middle">@med.UnitMeasureName</td>
                        <td class="align-middle">@med.CommodityName</td>
                    </tr>
                }

            </tbody>
        </table>
    }
    else
    {
        <div class="d-flex justify-content-center"><h3>Данних немає</h3></div>
    }
</div>

<script>
    $(function () {
        const addButtons = document.querySelectorAll(".ks-addbutton");

        const deleteButtons = document.querySelectorAll(".deleteButton");
        deleteButtons.forEach((button, index) => {
            if ((index + 1) % 2 === 0) {
                button.classList.add("ks-wbg");
            }
        })

        const editButtons = document.querySelectorAll(".editButton");
        editButtons.forEach((button, index) => {
            if ((index + 1) % 2 === 0) {
                button.classList.add("ks-wbg");
            }
        });

        $(editButtons).on('click', (event) => {
            event.preventDefault();
            $.get($(event.currentTarget).data("action"), (resp) => {
                $(".modal-contaier").html(resp);
                $('#idi').modal('show');
            })
        });

        $(addButtons).on('click', (event) => {
            event.preventDefault();
            $.get($(event.currentTarget).data("action"), (resp) => {
                $(".modal-contaier").html(resp);
                $('#idi').modal('show');
            })
        });
    });
</script>