Models/LaboratoryEmployee.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace PharmaKursWork.Models
{
    public class LaboratoryEmployee
    {
        public int Id { get; set; }

        [DisplayName("Ім'я")]
        [Required(ErrorMessage = "Вкажіть ім'я")]
        public string FirstName { get; set; } = string.Empty;

        [DisplayName("Прізвище")]
        [Required(ErrorMessage = "Вкажіть прізвище")]
        public string LastName { get; set; } = string.Empty;

        [DisplayName("Номер телефона")]
        [Required(ErrorMessage = "Вкажіть номер телефону")]
        public string PhoneNumber { get; set; } = string.Empty;

        [DisplayName("Email")]
        [Required(ErrorMessage = "Вкажіть email")]
        public string Email { get; set; } = string.Empty;

        [DisplayName("Адреса")]
        [Required(ErrorMessage = "Вкажіть адрес")]
        public string Adress { get; set; } = string.Empty;

        [DisplayName("Назва лабораторії")]
        [Required(ErrorMessage = "Вкажіть назву лабораторії")]
        public int LabratoryId { get; set; }

        [ForeignKey(nameof(LabratoryId))]
        public Laboratory Laboratory { get; set; }
    }
}

ViewModels/LaboratoryEmployeeViewModels/AddScientistViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using PharmaKursWork.Models;

namespace PharmaKursWork.ViewModels.LaboratoryEmployeeViewModels
{
    public class AddScientistViewModel
    {
        public LaboratoryEmployee LaboratoryEmployeeModel { get; set; }
        public Models.Scientist ScientistModel { get; set; }
        public SelectList LaboratorySelectList { get; set; }
    }
}

ViewModels/LaboratoryEmployeeViewModels/AddTechStaffViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using PharmaKursWork.Models;

namespace PharmaKursWork.ViewModels.LaboratoryEmployeeViewModels
{
    public class AddTechStaffViewModel
    {
        public LaboratoryEmployee LaboratoryEmployeeModel { get; set; }
        public TechStaff TechStaffModel { get; set; }
        public SelectList LaboratorySelectList { get; set; }
    }
}

ViewModels/LaboratoryEmployeeViewModels/EditScientistViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using PharmaKursWork.Models;

namespace PharmaKursWork.ViewModels.LaboratoryEmployeeViewModels
{
    public class EditScientistViewModel
    {
        public LaboratoryEmployee LaboratoryEmployeeModel { get; set; }
        public Models.Scientist ScientistModel { get; set; }
        public SelectList LaboratorySelectList { get; set; }
    }
}

ViewModels/LaboratoryEmployeeViewModels/EditTechStaffViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using PharmaKursWork.Models;

namespace PharmaKursWork.ViewModels.LaboratoryEmployeeViewModels
{
    public class EditTechStaffViewModel
    {
        public LaboratoryEmployee LaboratoryEmployeeModel { get; set; }
        public TechStaff TechStaffModel { get; set; }
        public SelectList LaboratorySelectList { get; set; }
    }
}

ViewModels/LaboratoryEmployeeViewModels/LaboratoryEmployeeViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using PharmaKursWork.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace PharmaKursWork.ViewModels.LaboratoryEmployeeViewModels
{
    public class LaboratoryEmployeeViewModel
    {
        public List<ScientistViewModel> ScientistList { get; set; }

        public ScientistViewModel ScientistViewModel{ get; set; }

        public List<TechStaffViewModel> TechStaffList { get; set; }

        public TechStaffViewModel TechStaffViewModel { get; set; }

        public SelectList LaboratorySelectList { get; set; }
    }

    public class ScientistViewModel
    {
        
        public int Id { get; set; }

        [DisplayName("Ім'я")]
        [Required(ErrorMessage = "Вкажіть ім'я")]
        public string FirstName { get; set; } = string.Empty;

        [DisplayName("Прізвище")]
        [Required(ErrorMessage = "Вкажіть прізвище")]
        public string LastName { get; set; } = string.Empty;

        [DisplayName("День рождения")]
        [Required(ErrorMessage = "Вкажіть день народження")]
        public DateTime BirthDate { get; set; } 

        [DisplayName("Номер телефон")]
        [Required(ErrorMessage = "Вкажіть номер телефону")]
        public string PhoneNumber { get; set; } = string.Empty;

        [DisplayName("Email")]
        [Required(ErrorMessage = "Вкажіть email")]
        public string Email { get; set; } = string.Empty;

        [DisplayName("Адреса")]
        [Required(ErrorMessage = "Вкажіть адреса")]
        public string Adress { get; set; } = string.Empty;

        [DisplayName("Назва лабораторії")]
        [Required(ErrorMessage = "Вкажіть назву лабораторії")]
        public string LaboratoryName { get; set; } = string.Empty;

        [DisplayName("Працює за приладом")]
        [Required(ErrorMessage = "Вкажіть прилад")]
        public string ResponsibleForDevice { get; set; } = string.Empty;

        [DisplayName("Напрямок досліджень")]
        [Required(ErrorMessage = "Вкажіть адресу лабораторії")]
        public string DirectionDevelopment { get; set; } = string.Empty;
    }
    public class TechStaffViewModel
    {
        public int Id { get; set; }

        [DisplayName("Ім'я")]
        [Required(ErrorMessage = "Вкажіть ім'я")]
        public string FirstName { get; set; } = string.Empty;

        [DisplayName("Прізвище")]
        [Required(ErrorMessage = "Вкажіть прізвище")]
        public string LastName { get; set; } = string.Empty;

        [DisplayName("День рождения")]
        [Required(ErrorMessage = "Вкажіть день народження")]
        public DateTime BirthDate { get; set; } 

        [DisplayName("Номер телефона")]
        [Required(ErrorMessage = "Вкажіть номер телефона")]
        public string PhoneNumber { get; set; } = string.Empty;

        [DisplayName("Email")]
        [Required(ErrorMessage = "Вкажіть email")]
        public string Email { get; set; } = string.Empty;

        [DisplayName("Адрес")]
        [Required(ErrorMessage = "Вкажіть адрес")]
        public string Adress { get; set; } = string.Empty;

        [DisplayName("Назва лабораторії")]
        [Required(ErrorMessage = "Вкажіть назву лабораторії")]
        public string LaboratoryName { get; set; } = string.Empty;

        [DisplayName("Обслуговує прилад")]
        [Required(ErrorMessage = "Вкажіть який прилад обслуговується")]
        public string MaintainsDevice { get; set; } = string.Empty;

        [DisplayName("Чи є свої інструменти")]
        [Required(ErrorMessage = "Вкажіть, чи є інструменти")]
        public bool HasYourInstruments { get; set; } 
    }

}

Controllers/LaboratoryEmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PharmaKursWork.Models;
using PharmaKursWork.Servises;
using PharmaKursWork.ViewModels.LaboratoryEmployeeViewModels;

namespace PharmaKursWork.Controllers
{
    public class LaboratoryEmployeeController : Controller
    {
        private readonly DataContext _db;
        private readonly UserServise _userServise;
        public LaboratoryEmployeeController(DataContext db, UserServise userService)
        {
            _db = db;
            _userServise = userService;
        }

        public async Task<IActionResult> Index()
        {
            var user = _userServise.getCurrentUser();

            if (user == null || user.Username == "Guest")
            {
                return RedirectToAction("Index", "Account");
            }

            var scientists = await (from s in _db.Scientists 
                                    join e in _db.LaboratoryEmployees on s.LaboratoryEmployeeId equals e.Id
                                    join l in _db.Laboratories on e.LabratoryId equals l.Id
                                    select new ScientistViewModel
                                    {
                                        Id = e.Id,
                                        FirstName= e.FirstName,
                                        LastName= e.LastName,
                                        PhoneNumber= e.PhoneNumber,
                                        Email= e.Email,
                                        ResponsibleForDevice = s.ResponsibleForDevice,
                                        Adress= e.Adress,
                                        DirectionDevelopment = s.DirectionDevelopment,
                                        LaboratoryName = l.Name
                                    }).ToListAsync();

            var techStaffs = await (from t in _db.TechStaffs
                                    join e in _db.LaboratoryEmployees on t.LaboratoryEmployeeId equals e.Id
                                    join l in _db.Laboratories on e.LabratoryId equals l.Id
                                    select new TechStaffViewModel
                                    {
                                        Id = e.Id,
                                        FirstName = e.FirstName,
                                        LastName = e.LastName,
                                        PhoneNumber = e.PhoneNumber,
                                        Email = e.Email,
                                        Adress = e.Adress,
                                        LaboratoryName = l.Name,
                                        HasYourInstruments = t.HasYourInstruments,
                                        MaintainsDevice = t.MaintainsDevice,
                                    }).ToListAsync();

            var labs = await (from l in _db.Laboratories select l).ToListAsync();

            var model = new LaboratoryEmployeeViewModel()
            {
                ScientistList = scientists,
                TechStaffList = techStaffs,
                LaboratorySelectList = new SelectList(labs, "Id", "Name"),
            };

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> AddScientist()
        {

            var labs = await (from l in _db.Laboratories select l).ToListAsync();

            var model = new AddScientistViewModel()
            {
                LaboratorySelectList = new SelectList(labs, "Id", "Name"),
            };

            return PartialView(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddScientist(AddScientistViewModel model)
        {
            var scientist = model.ScientistModel;
            var employee = model.LaboratoryEmployeeModel;

            await _db.LaboratoryEmployees.AddAsync(employee);
            await _db.SaveChangesAsync();
            scientist.LaboratoryEmployeeId = employee.Id;
            await _db.Scientists.AddAsync(scientist);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }
            
        [HttpGet]
        public async Task<IActionResult> EditScientist(int id)
        {
            var scientist = (from s in _db.Scientists where id == s.LaboratoryEmployeeId select s).FirstOrDefault();
            var employee = (from e in _db.LaboratoryEmployees where id == e.Id select e).FirstOrDefault();
            if (scientist == default || employee == default)
                return View("Index");

            var labs = await (from l in _db.Laboratories select l).ToListAsync();

            var model = new EditScientistViewModel
            {
                LaboratorySelectList = new SelectList(labs, "Id", "Name"),
                ScientistModel = scientist,
                LaboratoryEmployeeModel = employee,
            };

            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditScientist(EditScientistViewModel model)
        {
            var scientistData = model.ScientistModel;
            var employeeData = model.LaboratoryEmployeeModel;

            var scientist = (from s in _db.Scientists where employeeData.Id == s.LaboratoryEmployeeId select s).FirstOrDefault();
            var employee = (from e in _db.LaboratoryEmployees where employeeData.Id == e.Id select e).FirstOrDefault();
                
            if (scientist == default || employee == default)
                return View("Index");

            scientist.DirectionDevelopment = scientistData.DirectionDevelopment;
            scientist.ResponsibleForDevice = scientistData.ResponsibleForDevice;

            employee.FirstName = employeeData.FirstName;
            employee.LastName = employeeData.LastName;
            employee.PhoneNumber = employeeData.PhoneNumber;
            employee.Adress = employeeData.Adress;
            employee.Email = employeeData.Email;
            employee.LabratoryId = employeeData.LabratoryId;

            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> AddTechStaff()
        {

            var labs = await (from l in _db.Laboratories select l).ToListAsync();

            var model = new AddTechStaffViewModel()
            {
                LaboratorySelectList = new SelectList(labs, "Id", "Name"),
            };

            return PartialView(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddTechStaff(AddTechStaffViewModel model)
        {
            var techStaff = model.TechStaffModel;
            var emp = model.LaboratoryEmployeeModel;

            await _db.LaboratoryEmployees.AddAsync(emp);
            await _db.SaveChangesAsync();
            techStaff.LaboratoryEmployeeId = emp.Id;
            await _db.TechStaffs.AddAsync(techStaff);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditTechStaff(int id)
        {
            var techStaff = (from t in _db.TechStaffs where id == t.LaboratoryEmployeeId select t).FirstOrDefault();
            var employee = (from e in _db.LaboratoryEmployees where id == e.Id select e).FirstOrDefault();

            if (employee == default || techStaff == default)
                return View("Index");

            var labs = await (from l in _db.Laboratories select l).ToListAsync();

            var model = new EditTechStaffViewModel
            {
                LaboratorySelectList = new SelectList(labs, "Id", "Name"),
                TechStaffModel = techStaff,
                LaboratoryEmployeeModel = employee,
            };

            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditTechStaff(EditTechStaffViewModel model)
        {
            var techStaffData = model.TechStaffModel;
            var employeeData = model.LaboratoryEmployeeModel;

            var techStaff = (from t in _db.TechStaffs where employeeData.Id == t.LaboratoryEmployeeId select t).FirstOrDefault();
            var employee = (from e in _db.LaboratoryEmployees where employeeData.Id == e.Id select e).FirstOrDefault();

            if (techStaff == default || employee == default)
                return View("Index");

            techStaff.MaintainsDevice = techStaffData.MaintainsDevice;
            techStaff.HasYourInstruments = techStaffData.HasYourInstruments;

            employee.FirstName = employeeData.FirstName;
            employee.LastName = employeeData.LastName;
            employee.PhoneNumber = employeeData.PhoneNumber;
            employee.Adress = employeeData.Adress;
            employee.Email = employeeData.Email;
            employee.LabratoryId = employeeData.LabratoryId;

            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteScientist(int id)
        {
            var scientist = (from c in _db.Scientists where c.LaboratoryEmployeeId == id select c).FirstOrDefault();
            var employee = (from e in _db.LaboratoryEmployees where e.Id == id select e).FirstOrDefault();

            if (scientist == default || employee == default)
                return View("Index");
            var challenge = _db.Challenges.FirstOrDefault(u => u.ScientistId == scientist.LaboratoryEmployeeId);
            if (challenge != default)
                return RedirectToAction("Index");

            _db.Scientists.Remove(scientist);
            _db.LaboratoryEmployees.Remove(employee);

            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteTechStaff(int id)
        {

Views/LaboratoryEmployee/AddScientist.cshtml
@model PharmaKursWork.ViewModels.LaboratoryEmployeeViewModels.AddScientistViewModel;
@{
    Layout = null;
}

<div id="idi" class="modal fade" tabindex="-1" aria-labelledby="editModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Додати вченого</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-action="AddScientist" asp-controller="LaboratoryEmployee">
                    <input type="hidden" asp-for="LaboratoryEmployeeModel.Id" />
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="FirstName" class="col-form-label">@Html.DisplayNameFor(_ => Model.LaboratoryEmployeeModel.FirstName)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="LaboratoryEmployeeModel.FirstName" class="form-control" id="FirstName" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="LastName" class="col-form-label">@Html.DisplayNameFor(_ => Model.LaboratoryEmployeeModel.LastName)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="LaboratoryEmployeeModel.LastName" class="form-control" id="LastName" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="PhoneNumber" class="col-form-label">@Html.DisplayNameFor(_ => Model.LaboratoryEmployeeModel.PhoneNumber)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="LaboratoryEmployeeModel.PhoneNumber" class="form-control" id="PhoneNumber" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="Email" class="col-form-label">@Html.DisplayNameFor(_ => Model.LaboratoryEmployeeModel.Email)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="LaboratoryEmployeeModel.Email" class="form-control" id="Email" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="Adress" class="col-form-label">@Html.DisplayNameFor(_ => Model.LaboratoryEmployeeModel.Adress)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="LaboratoryEmployeeModel.Adress" class="form-control" id="Adress" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="commodityGroup" class="form-label">@Html.DisplayNameFor(_ => Model.LaboratoryEmployeeModel.LabratoryId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="LaboratoryEmployeeModel.LabratoryId" asp-items="Model.LaboratorySelectList" required></select>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="ResponsibleForDevice" class="col-form-label">@Html.DisplayNameFor(_ => Model.ScientistModel.ResponsibleForDevice )</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="ScientistModel.ResponsibleForDevice" class="form-control" id="ResponsibleForDevice" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="DirectionDevelopment" class="col-form-label">@Html.DisplayNameFor(_ => Model.ScientistModel.DirectionDevelopment)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="ScientistModel.DirectionDevelopment" class="form-control" id="DirectionDevelopment" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
                        <button type="submit" class="btn btn-primary">Додати</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/LaboratoryEmployee/AddTechStaff.cshtml
@model PharmaKursWork.ViewModels.LaboratoryEmployeeViewModels.AddTechStaffViewModel;
@{
    Layout = null;
}

<div id="idi" class="modal fade" tabindex="-1" aria-labelledby="editModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Додати тех персонал</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-action="AddTechStaff" asp-controller="LaboratoryEmployee">
                    <input type="hidden" asp-for="LaboratoryEmployeeModel.Id" />
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="FirstName" class="col-form-label">@Html.DisplayNameFor(_ => Model.LaboratoryEmployeeModel.FirstName)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="LaboratoryEmployeeModel.FirstName" class="form-control" id="FirstName" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="LastName" class="col-form-label">@Html.DisplayNameFor(_ => Model.LaboratoryEmployeeModel.LastName)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="LaboratoryEmployeeModel.LastName" class="form-control" id="LastName" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="PhoneNumber" class="col-form-label">@Html.DisplayNameFor(_ => Model.LaboratoryEmployeeModel.PhoneNumber)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="LaboratoryEmployeeModel.PhoneNumber" class="form-control" id="PhoneNumber" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="Email" class="col-form-label">@Html.DisplayNameFor(_ => Model.LaboratoryEmployeeModel.Email)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="LaboratoryEmployeeModel.Email" class="form-control" id="Email" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="Adress" class="col-form-label">@Html.DisplayNameFor(_ => Model.LaboratoryEmployeeModel.Adress)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="LaboratoryEmployeeModel.Adress" class="form-control" id="Adress" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="commodityGroup" class="form-label">@Html.DisplayNameFor(_ => Model.LaboratoryEmployeeModel.LabratoryId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="LaboratoryEmployeeModel.LabratoryId" asp-items="Model.LaboratorySelectList" required></select>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="ResponsibleForDevice" class="col-form-label">@Html.DisplayNameFor(_ => Model.TechStaffModel.HasYourInstruments)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select asp-for="TechStaffModel.HasYourInstruments" class="form-control" id="ResponsibleForDevice" required>
                                <option value="true">true</option>
                                <option value="false">false</option>
                            </select>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="DirectionDevelopment" class="col-form-label">@Html.DisplayNameFor(_ => Model.TechStaffModel.MaintainsDevice)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="TechStaffModel.MaintainsDevice" class="form-control" id="DirectionDevelopment" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
                        <button type="submit" class="btn btn-primary">Додати</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>