Models/Challenge.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace PharmaKursWork.Models
{
    public class Challenge
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public DateTime ChallegesStart { get; set; }

        public int ScientistId { get; set; }
        [ForeignKey(nameof(ScientistId))]
        public Scientist Scientist { get; set; }
        
        public int MedsId { get; set; }
        [ForeignKey(nameof(MedsId))]
        public Med Med { get; set; }

        public int TechStaffId { get; set; }

        [ForeignKey(nameof(TechStaffId))]
        public TechStaff TechStaff{ get; set; }

    }
}

ViewModels/ChallengeViewModels/AddChallengeViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PharmaKursWork.ViewModels.ChallengeViewModels
{
    public class AddChallengeViewModel
    {
        public AddChallengeModal AddChallengeModal { get; set; }
        public SelectList MedSelectList { get; set; }
        public SelectList ScientistSelectList { get; set; }
        public SelectList TechStaffSelectList { get; set; }
        
    }
    
    public class AddChallengeModal
    {
        public int Id { get; set; }

        [DisplayName("Назва")]
        [Required(ErrorMessage = "Вкажіть назву")]
        public string Name { get; set; }

        [DisplayName("Початок випробування")]
        [Required(ErrorMessage = "Вкажіть початок випробування")]
        public DateTime ChallegesStart { get; set; }
        
        [DisplayName("Кінець випробування")]
        [Required(ErrorMessage = "Вкажіть кінець випробування")]
        public DateTime ChallegesEnd { get; }

        [DisplayName("Випробування займається")]
        [Required(ErrorMessage = "Вкажіть Вченого")]
        public int ScientistId { get; set; }

        [DisplayName("Назва ліків")]
        [Required(ErrorMessage = "Вкажіть назву")]
        public int MedId { get; set; }

        [DisplayName("Відповідальний за роботу приладів")]
        [Required(ErrorMessage = "Вкажіть тих персонал")]
        public int TechStaffId { get; set; }
    }
}

ViewModels/ChallengeViewModels/ChallengeViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PharmaKursWork.ViewModels.ChallengeViewModels
{
    public class ChallengeView
    {
        public int Id { get; set; }

        [DisplayName("Назва")]
        [Required(ErrorMessage = "Вкажіть назву")]
        public string Name { get; set; } = string.Empty;

        [DisplayName("Початок випробування")]
        [Required(ErrorMessage = "Вкажіть початок випробування")]
        public DateTime ChallegesStart { get; set; }

        [DisplayName("Випробування займається")]
        [Required(ErrorMessage = "Вкажіть Вченого")]
        public string ScientistName { get; set; } = string.Empty;

        [DisplayName("Назва ліків")]
        [Required(ErrorMessage = "Вкажіть назву")]
        public string MedName { get; set; } = string.Empty;

        [DisplayName("Відповідальний за роботу приладів")]
        [Required(ErrorMessage = "Вкажіть тих персонал")]
        public string TechStaffName { get; set; } = string.Empty;
    }
    public class ChallengeViewModel
    {
        public SelectList MedSelectList { get; set; }
        public AddChallengeViewModel AddView { get; set; }
        public ChallengeView View { get; set; }
        public List<ChallengeView> List { get; set; }
        public FilterViewModel FilterViewModel { get; set; }
    }

    public class FilterViewModel
    {

        [DisplayName("Мінімальна дата")]
        public DateTime MinChallegesStart { get; set; }

        [DisplayName("Максимальна дата")]
        public DateTime MaxChallegesStart { get; set; }

        [DisplayName("Назва")]
        public string Name { get; set; }
    }
}

ViewModels/ChallengeViewModels/EditChallengeViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PharmaKursWork.ViewModels.ChallengeViewModels
{
    public class EditChallengeViewModel
    {
        public EditChallengeModal EditChallengeModal { get; set; }
        public SelectList MedSelectList { get; set; }
        public SelectList ScientistSelectList { get; set; }
        public SelectList TechStaffSelectList { get; set; }
    }

    public class EditChallengeModal
    {
        public int Id { get; set; }

        [DisplayName("Назва")]
        [Required(ErrorMessage = "Вкажіть назву")]
        public string Name { get; set; }

        [DisplayName("Початок випробування")]
        [Required(ErrorMessage = "Вкажіть початок випробування")]
        public DateTime ChallegesStart { get; set; }

        [DisplayName("Кінець випробування")]
        [Required(ErrorMessage = "Вкажіть кінець випробування")]
        public DateTime ChallegesEnd { get; }

        [DisplayName("Вкажіть кінець випробування")]
        [Required(ErrorMessage = "Вкажіть Вченого")]
        public int ScientistId { get; set; }

        [DisplayName("Назва ліків")]
        [Required(ErrorMessage = "Вкажіть назву")]
        public int MedId { get; set; }

        [DisplayName("Відповідальний за роботу приладів")]
        [Required(ErrorMessage = "Вкажіть тих персонал")]
        public int TechStaffId { get; set; }
    }
}

Controllers/ChallengeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using PharmaKursWork.Models;
using PharmaKursWork.Servises;
using PharmaKursWork.ViewModels.ChallengeViewModels;
using PharmaKursWork.ViewModels.MedViewModels;

namespace PharmaKursWork.Controllers
{
    public class ChallengeController : Controller
    {
        private readonly DataContext _db;
        private readonly UserServise _userServise;
        public ChallengeController(DataContext db, UserServise userService)
        {
            _db = db;
            _userServise = userService;
        }
        [HttpGet]
        public IActionResult Index(ChallengeViewModel? challengeModel)
        {
            var user = _userServise.getCurrentUser();


            if (user == null || user.Username == "Guest")
            {
                return RedirectToAction("Index", "Account");
            }

            var filter = challengeModel.FilterViewModel;

            var meds = (from m in _db.Meds select m);
            var scientist = (from s in _db.Scientists
                             join e in _db.LaboratoryEmployees on s.LaboratoryEmployeeId equals e.Id
                             select new { Name = e.FirstName, Id = e.Id });

            var techStaff = (from t in _db.TechStaffs
                             join e in _db.LaboratoryEmployees on t.LaboratoryEmployeeId equals e.Id
                             select new { Name = e.FirstName, Id = e.Id });

            var challenges = (from c in _db.Challenges
                              join m in _db.Meds on c.MedsId equals m.Id
                              join s in scientist on c.ScientistId equals s.Id
                              join t in techStaff on c.TechStaffId equals t.Id
                              select new ChallengeView()
                              {
                                  Id = c.Id,
                                  Name = c.Name,
                                  ChallegesStart = c.ChallegesStart,
                                  MedName = m.Name,
                                  ScientistName = s.Name,
                                  TechStaffName = t.Name,
                              });

            if (filter != null)
            {
                if (!string.IsNullOrEmpty(filter.Name))
                {
                    challenges = challenges.Where(m => m.Name.Contains(filter.Name));
                }

                if (filter.MinChallegesStart != DateTime.MinValue)
                {
                    challenges = challenges.Where(m => m.ChallegesStart > filter.MinChallegesStart);
                }
                if (filter.MaxChallegesStart != DateTime.MinValue)
                {
                    challenges = challenges.Where(m => m.ChallegesStart < filter.MaxChallegesStart);
                }
            }

            var model = new ChallengeViewModel
            {
                List = challenges.ToList(),
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddChallenge()
        {
            var meds = await (from m in _db.Meds
                              select m).ToListAsync();
            var scientists = await (from s in _db.Scientists
                                    join e in _db.LaboratoryEmployees on s.LaboratoryEmployeeId equals e.Id
                                    select new { Id = s.LaboratoryEmployeeId, Name = e.FirstName }).ToListAsync();

            var techStaffs = await (from c in _db.TechStaffs
                                    join e in _db.LaboratoryEmployees on c.LaboratoryEmployeeId equals e.Id
                                    select new { Id = c.LaboratoryEmployeeId, Name = e.FirstName }).ToListAsync();

            var model = new AddChallengeViewModel
            {
                MedSelectList = new SelectList(meds, "Id", "Name"),
                ScientistSelectList = new SelectList(scientists, "Id", "Name"),
                TechStaffSelectList = new SelectList(techStaffs, "Id", "Name"),
            };

            return PartialView(model);
        }


        [HttpPost]
        public async Task<IActionResult> AddChallenge(AddChallengeViewModel model)
        {
            var addData = model.AddChallengeModal;
            var challenge = new Challenge
            {
                Name = addData.Name,
                ChallegesStart = DateTime.Now,
                MedsId = addData.MedId,
                ScientistId = addData.ScientistId,
                TechStaffId = addData.TechStaffId,
            };

            await _db.Challenges.AddAsync(challenge);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditChallenge(int id)
        {
            var meds = await (from m in _db.Meds
                              select m).ToListAsync();
            var scientists = await (from s in _db.Scientists
                                    join e in _db.LaboratoryEmployees on s.LaboratoryEmployeeId equals e.Id
                                    select new { Id = s.LaboratoryEmployeeId, Name = e.FirstName }).ToListAsync();

            var techStaffs = await (from c in _db.TechStaffs
                                    join e in _db.LaboratoryEmployees on c.LaboratoryEmployeeId equals e.Id
                                    select new { Id = c.LaboratoryEmployeeId, Name = e.FirstName }).ToListAsync();


            var rawChallenge = (from c in _db.Challenges
                                where c.Id == id
                                select c).FirstOrDefault();
            if (rawChallenge == default)
                return View("Index");

            var challenge = new EditChallengeModal
            {
                Id = rawChallenge.Id,
                Name = rawChallenge.Name,
                MedId = rawChallenge.MedsId,
                ScientistId = rawChallenge.ScientistId,
                TechStaffId = rawChallenge.TechStaffId,
            };
            var model = new EditChallengeViewModel
            {
                EditChallengeModal = challenge,
                MedSelectList = new SelectList(meds, "Id", "Name"),
                ScientistSelectList = new SelectList(scientists, "Id", "Name"),
                TechStaffSelectList = new SelectList(techStaffs, "Id", "Name"),
            };

            return PartialView(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditChallenge(EditChallengeViewModel model)
        {
            var editData = model.EditChallengeModal;
            var challenge = (from c in _db.Challenges
                             where c.Id == editData.Id
                             select c).FirstOrDefault();
            if (challenge == default) 
            {
                return View("Index");
            }

            challenge.Name = editData.Name;
            challenge.ChallegesStart = editData.ChallegesStart;
            challenge.MedsId = editData.MedId;
            challenge.ScientistId = editData.ScientistId;
            challenge.TechStaffId = editData.TechStaffId;
            
            await _db.SaveChangesAsync();


            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var challenge = (from c in _db.Challenges where c.Id == id select c).FirstOrDefault();
            if (challenge == default)
                return View("Index");

            _db.Challenges.Remove(challenge);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/Challenge/AddChallenge.cshtml
@model PharmaKursWork.ViewModels.ChallengeViewModels.AddChallengeViewModel;
@{
    Layout = null;
}

<div id="idi" class="modal fade" tabindex="-1" aria-labelledby="editModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Додати випробування</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-action="AddChallenge" asp-controller="Challenge">
                    <input type="hidden" asp-for="AddChallengeModal.Id" />
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="Name" class="col-form-label">@Html.DisplayNameFor(_ => Model.AddChallengeModal.Name)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="AddChallengeModal.Name" class="form-control" id="Name" required>
                            <span asp-validation-for="AddChallengeModal.Name"></span>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="lab" class="form-label">@Html.DisplayNameFor(_ => Model.AddChallengeModal.ScientistId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="AddChallengeModal.ScientistId" asp-items="Model.ScientistSelectList" required></select>
                            <span asp-validation-for="AddChallengeModal.ScientistId"></span>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="unitMesuare" class="form-label">@Html.DisplayNameFor(_ => Model.AddChallengeModal.TechStaffId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="AddChallengeModal.TechStaffId" asp-items="Model.TechStaffSelectList" required></select>
                            <span asp-validation-for="AddChallengeModal.TechStaffId"></span>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="commodityGroup" class="form-label">@Html.DisplayNameFor(_ => Model.AddChallengeModal.MedId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="AddChallengeModal.MedId" asp-items="Model.MedSelectList" required></select>
                            <span asp-validation-for="AddChallengeModal.MedId"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
                        <button type="submit" class="btn btn-primary">Додати</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Challenge/EditChallenge.cshtml
@model PharmaKursWork.ViewModels.ChallengeViewModels.EditChallengeViewModel;
@{
    Layout = null;
}

<div id="idi" class="modal fade" tabindex="-1" aria-labelledby="editModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Змінити випробування</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-action="EditChallenge" asp-controller="Challenge">
                    <input type="hidden" asp-for="EditChallengeModal.Id" required/>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="Name" class="col-form-label">@Html.DisplayNameFor(_ => Model.EditChallengeModal.Name)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="EditChallengeModal.Name" class="form-control" id="Name" required>
                            <span asp-validation-for="EditChallengeModal.Name"></span>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="lab" class="form-label">@Html.DisplayNameFor(_ => Model.EditChallengeModal.ScientistId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="EditChallengeModal.ScientistId" asp-items="Model.ScientistSelectList" required></select>
                            <span asp-validation-for="EditChallengeModal.ScientistId"></span>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="unitMesuare" class="form-label">@Html.DisplayNameFor(_ => Model.EditChallengeModal.TechStaffId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="EditChallengeModal.TechStaffId" asp-items="Model.TechStaffSelectList" required></select>
                            <span asp-validation-for="EditChallengeModal.TechStaffId"></span>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="commodityGroup" class="form-label">@Html.DisplayNameFor(_ => Model.EditChallengeModal.MedId)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <select class="form-control" asp-for="EditChallengeModal.MedId" asp-items="Model.MedSelectList" required></select>
                            <span asp-validation-for="EditChallengeModal.MedId"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
                        <button type="submit" class="btn btn-primary">Змінити</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Challenge/Index.cshtml
@model PharmaKursWork.ViewModels.ChallengeViewModels.ChallengeViewModel
@inject PharmaKursWork.Servises.UserServise userService;
@{
    var isCurrentUserAdmin = userService.isCurrentUserAdmin();
}
<div class="text-center">
    <div>
        <form asp-action="Index" asp-controller="Challenge" method="get">
            <div class="mb-3 row align-items-center">
                <div class="col-auto">
                    <label for="MedName" class="col-form-label">@Html.DisplayNameFor(_ => Model.FilterViewModel.Name)</label>
                </div>
                <div class="col-auto flex-grow-1">
                    <input asp-for="FilterViewModel.Name" class="form-control" id="MedName">
                </div>
            </div>
            <div class="mb-3 row align-items-center">
                <div class="col-auto">
                    <label for="Expenses" class="col-form-label">@Html.DisplayNameFor(_ => Model.FilterViewModel.MinChallegesStart)</label>
                </div>
                <div class="col-auto flex-grow-1">
                    <input asp-for="FilterViewModel.MinChallegesStart" class="form-control" id="Expenses">
                </div>
            </div>
            <div class="mb-3 row align-items-center">
                <div class="StartExploring">
                    <label for="FirstName" class="col-form-label">@Html.DisplayNameFor(_ => Model.FilterViewModel.MaxChallegesStart)</label>
                </div>
                <div class="col-auto flex-grow-1">
                    <input asp-for="FilterViewModel.MaxChallegesStart" class="form-control" id="StartExploring">
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Пошук</button>
        </form>
        <a class="btn btn-primary mt-2" asp-action="Index" asp-controller="Challenge">Скинути</a>
    </div>
    @if (isCurrentUserAdmin) {
        <button type="button" 
                class="btn btn-primary ks-addbutton rounded-circle d-flex p-3"
            data-action="@Url.Action("AddChallenge", "Challenge")">
            <img style="width: 40px; height: 40px" src="icons/plus.svg" />
        </button>
    }
    <div class="modal-container"></div>
    <!-- Modal -->
    @if (Model.List.Count > 0)
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <td></td>
                    <td>@Html.DisplayNameFor(_ => Model.View.Name)</td>
                    <td>@Html.DisplayNameFor(_ => Model.View.ChallegesStart)</td>
                    <td>@Html.DisplayNameFor(_ => Model.View.MedName)</td>
                    <td>@Html.DisplayNameFor(_ => Model.View.TechStaffName)</td>
                    <td>@Html.DisplayNameFor(_ => Model.View.ScientistName)</td>
                </tr>
            </thead>
            <tbody>

                @foreach (var chal in Model.List)
                {
                    <tr>
                        <td class="align-middle">
                            @if(isCurrentUserAdmin)
                            {
                                <button class="ks-tablebuttons editButton" data-action="@Url.Action("EditChallenge", "Challenge", new { id = chal.Id })"><img src="icons/pencil-square.svg" /></button>
                                <a class="ks-tablebuttons deleteButton" asp-action="Delete" asp-controller="Challenge" asp-route-id="@chal.Id"><img src="icons/trash3-fill.svg" /></a>
                            }
                        </td>
                        <td class="align-middle">@chal.Name</td>
                        <td class="align-middle">@chal.ChallegesStart</td>
                        <td class="align-middle">@chal.MedName</td>
                        <td class="align-middle">@chal.TechStaffName</td>
                        <td class="align-middle">@chal.ScientistName</td>
                    </tr>
                }

            </tbody>
        </table>
    }
    else
    {
        <div class="d-flex justify-content-center"><h3>Данних немає</h3></div>
    }
</div>

<script>
    $(function () {
        const addButtons = document.querySelectorAll(".ks-addbutton");

        const deleteButtons = document.querySelectorAll(".deleteButton");
        deleteButtons.forEach((button, index) => {
            if ((index + 1) % 2 === 0) {
                button.classList.add("ks-wbg");
            }
        })

        const editButtons = document.querySelectorAll(".editButton");
        editButtons.forEach((button, index) => {
            if ((index + 1) % 2 === 0) {
                button.classList.add("ks-wbg");
            }
        });

        $(editButtons).on('click', (event) => {
            event.preventDefault();
            $.get($(event.currentTarget).data("action"), (resp) => {
                $(".modal-container").html(resp);
                $('#idi').modal('show');
            })
        });

        $(addButtons).on('click', (event) => {
            event.preventDefault();
            $.get($(event.currentTarget).data("action"), (resp) => {
                $(".modal-container").html(resp);
                $('#idi').modal('show');
            })
        });
    });
</script>