ViewModels/UnitViewModels/UnitViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PharmaKursWork.Models;

namespace PharmaKursWork.ViewModels.UnitViewModels
{
    public class UnitViewModel
    {
        public int Id { get; set; }

        [DisplayName("Назва")]
        [Required(ErrorMessage = "Вкажіть назву одиниці виміру")]
        public string Name { get; set; }

        [DisplayName("Опис")]
        [Required(ErrorMessage = "Вкажіть опис одиниці вимірювання")]
        public string Desc { get; set; }

        public List<UnitMeasure> List { get; set; } = new List<UnitMeasure>();
    }
}

Controllers/UnitController.cs
using Microsoft.AspNetCore.Mvc;
using PharmaKursWork.Models;
using PharmaKursWork.Servises;
using PharmaKursWork.ViewModels.UnitViewModels;

namespace PharmaKursWork.Controllers
{
    public class UnitController : Controller
    {
        private readonly DataContext _db;
        private readonly UserServise _userServise;
        public UnitController(DataContext db, UserServise userService)
        {
            _db = db;
            _userServise = userService;
        }

        public IActionResult Index()
        {
            var user = _userServise.getCurrentUser();

            if (user == null || user.Username == "Guest")
            {
                return RedirectToAction("Index", "Account");
            }

            var model = new UnitViewModel
            {
                List = _db.UnitMeasures.ToList(),
            };

            return View(model);
        }
        [HttpGet]
        public IActionResult AddUnit()
        {
            return PartialView();
        }

        public async Task<IActionResult> AddUnit(AddUnitModalViewModel unitData)
        {
            var unit = new UnitMeasure
            {
                Name = unitData.Name,
                Desc = unitData.Desc,
            };

            await _db.UnitMeasures.AddAsync(unit);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditUnit(int id)
        {
            var unit = _db.UnitMeasures.FirstOrDefault(u => u.Id == id);
            if (unit == default)
                return View("Index");
            var model = new EditUnitModalViewModel
            {
                Id = unit.Id,
                Name = unit.Name,
                Desc = unit.Desc,
            };

            return PartialView(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditUnit(EditUnitModalViewModel unitData)
        {
            var unit = _db.UnitMeasures.First(u => u.Id == unitData.Id);
            if (unit == default)
                return View("Index");
            unit.Name = unitData.Name;
            unit.Desc = unitData.Desc;

            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var unit = _db.UnitMeasures.FirstOrDefault(u => u.Id == id);
            if (unit == default)
                return View("Index");

            _db.UnitMeasures.Remove(unit);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }


    }
}

Views/Unit/AddUnit.cshtml
@model PharmaKursWork.ViewModels.UnitViewModels.AddUnitModalViewModel;
@{
    Layout = null;
}

<div id="idi" class="modal fade" tabindex="-1" aria-labelledby="editModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Додати одиницю виміру</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-action="AddUnit" asp-controller="Unit">
                    <input type="hidden" asp-for="Id" />
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="Name" class="col-form-label">@Html.DisplayNameFor(_ => Model.Name)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="Name" class="form-control" id="Name" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="startExp" class="form-label">@Html.DisplayNameFor(_ => Model.Desc)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="Desc" class="form-control" id="startExp" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
                        <button type="submit" class="btn btn-primary">Додати</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Unit/EditUnit.cshtml
@model PharmaKursWork.ViewModels.UnitViewModels.EditUnitModalViewModel;
@{
    Layout = null;
}

<div id="idi" class="modal fade" tabindex="-1" aria-labelledby="editModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Змінити одиницю виміру</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-action="EditUnit" asp-controller="Unit">
                    <input type="hidden" asp-for="Id" />
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="Name" class="col-form-label">@Html.DisplayNameFor(_ => Model.Name)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="Name" class="form-control" id="Name" required>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <div class="col-auto">
                            <label for="startExp" class="form-label">@Html.DisplayNameFor(_ => Model.Desc)</label>
                        </div>
                        <div class="col-auto flex-grow-1">
                            <input asp-for="Desc" class="form-control" id="startExp" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрити</button>
                        <button type="submit" class="btn btn-primary">Змінити</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Unit/Index.cshtml
@model PharmaKursWork.ViewModels.UnitViewModels.UnitViewModel;

<div class="text-center">
    <!-- Button trigger modal -->
    <button type="button"
            class="btn btn-primary ks-addbutton rounded-circle d-flex p-3"
            data-action="@Url.Action("AddUnit", "Unit")">

        <img style="width: 40px; height: 40px" src="icons/plus.svg" />
    </button>

    <div class="modal-contaier">
    </div>

    @if (Model.List.Count > 0)
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <td></td>
                    <td>@Html.DisplayNameFor(_ => Model.Name)</td>
                    <td>@Html.DisplayNameFor(_ => Model.Desc)</td>
                </tr>
            </thead>
            <tbody>

                @foreach (var unit in Model.List)
                {
                    <tr>
                        <td class="align-middle">
                            <button class="ks-tablebuttons editButton" data-action="@Url.Action("EditUnit", "Unit", new { id = unit.Id })"><img src="icons/pencil-square.svg" /></button>
                            <a class="ks-tablebuttons deleteButton" asp-action="Delete" asp-controller="Unit" asp-route-id="@unit.Id"><img src="icons/trash3-fill.svg" /></a>
                        </td>
                        <td class="align-middle">@unit.Name</td>
                        <td class="align-middle">@unit.Desc</td>
                    </tr>
                }

            </tbody>
        </table>
    } 
    else
    {
        <div class="d-flex justify-content-center"><h3>Данних немає</h3></div>
    }
</div>

<script>
    $(function () {
        const addButtons = document.querySelectorAll(".ks-addbutton");

        const deleteButtons = document.querySelectorAll(".deleteButton");
        deleteButtons.forEach((button, index) => {
            if ((index + 1) % 2 === 0) {
                button.classList.add("ks-wbg");
            }
        })

        const editButtons = document.querySelectorAll(".editButton");
        editButtons.forEach((button, index) => {
            if ((index + 1) % 2 === 0) {
                button.classList.add("ks-wbg");
            }
        });

        $(editButtons).on('click', (event) => {
            event.preventDefault();
            $.get($(event.currentTarget).data("action"), (resp) => {
                $(".modal-contaier").html(resp);
                $('#idi').modal('show');
            })
        });

        $(addButtons).on('click', (event) => {
            event.preventDefault();
            $.get($(event.currentTarget).data("action"), (resp) => {
                $(".modal-contaier").html(resp);
                $('#idi').modal('show');
            })
        });
    });
</script>